Feat/avatar icon
JonnoKiwi/initiative-tree pull request #26
Opened 2020-12-23 21:24 UTC by JonnoKiwi

Closes: https://github.com/JonnoKiwi/initiative-tree/issues/25

2020-12-28 09:37 UTC, johntimothybailey requested changes
@JonnoKiwi Avatar and Icon seem to be very overlapping terms. Why `AvatarIcon` instead of just `Avatar`?

2020-12-28 21:22 UTC, JonnoKiwi commented
> @JonnoKiwi Avatar and Icon seem to be very overlapping terms. Why `AvatarIcon` instead of just `Avatar`?

I had a conflict with using the name "avatar". I have resolved the conflict. Now the naming is more clear.

2020-12-28 23:43 UTC, johntimothybailey requested changes
Move it to `components/`

2020-12-28 23:43 UTC, johntimothybailey commented on app/screens/Dashboard/UserListItem.tsx
> +        <Avatar avatar={avatar} />
`thumbail={avatar.thumbnail}`

2020-12-28 23:43 UTC, johntimothybailey commented on app/screens/Dashboard/Avatar.tsx
> +  const image = (avatar === undefined) ? defaultImage : { uri: avatar.thumbnail }
```
import R from 'ramda'
export default ({thumbnail}) => {
    const image = R.is(String, thumbnail) ? {  uri: thumbnail } : defaultImage
```

2020-12-28 23:43 UTC, johntimothybailey commented on app/screens/Dashboard/Avatar.story.tsx
> +        <Avatar />
Add a case for 

```
<Avatar thumbnail={null} />
<Avatar thumbnail="" />
```

2020-12-29 22:25 UTC, johntimothybailey approved these changes

2020-12-29 22:25 UTC, merged